name: Puppeteer Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: List files in the directory
      run: ls -al

    - name: Install dependencies
      run: |
        npm install

    - name: Run Puppeteer scraper
      run: |
        node main.js  # Ensure this file exists in the root of your repo

    - name: Upload Excel output
      uses: actions/upload-artifact@v3
      with:
        name: scraper-output
        path: 'output/*.xlsx'  # Changed path to reflect 'output' directory where the Excel file is saved
